apiVersion: v1alpha1
kind: AnnotationSetting
metadata:
  generateName: annotation-setting-
spec:
  targetRef:
    group: ""
    kind: MenuItem
  formSchema:
    - $formkit: "text"
      name: "icon"
      label: "图标"

---
apiVersion: v1alpha1
kind: AnnotationSetting
metadata:
  generateName: annotation-setting-
spec:
  targetRef:
    group: content.halo.run
    kind: Post
  formSchema:
    - $formkit: "radio"
      name: "enable_h_icon"
      label: "启用标题图标"
      help: "启用h1~h6标题左边图标 仅限于当前文章"
      value: "true"
      options:
        - label: 启用
          value: "true"
        - label: 禁用
          value: "false"
      