apiVersion: v1alpha1
kind: BaseSetting
metadata:
  name: theme-butterfly-setting
spec:
  forms:
    - group: base
      label: 基本
      formSchema:
        - $formkit: text
          name: metadata_name
          label: 作者的唯一标识 metadata.name
          placeholder: 请填写 作者的唯一标识 metadata.name
          value: admin
          help: 后台用户管理中的用户名，不可乱填否则个人资料显示异常（示例：admin）
          validation: required
        - $formkit: text
          name: icp
          label: ICP 备案号
          placeholder: 请填写 ICP 备案号信息
          help: ICP 备案信息将展示在页脚中，不填不展示（示例：蜀ICP备xx号）
        - $formkit: text
          name: police
          label: 公网安备号
          placeholder: 请填写公网安备号信息
          help: 公网安备信息将展示在页脚中，不填不展示（示例：京公xxx号）
        - $formkit: date
          name: site_birthday
          label: 建站时间
          placeholder: 示例 2022-01-01 00:00
          help: 自定义博客的起始时间/安装时间，作为计算博客运行时间的参照值，请严格按照示例格式填写，否则将导致报错

    - group: style
      label: 主题
      formSchema:
        - $formkit: select
          name: theme_mode
          label: 主题模式
          value: 'user'
          placeholder: 请填写主题颜色
          help: '设置博客的主题模式（自动/用户/浅色/深色），默认为用户模式，仅在用户模式下页面才有主题切换按钮，自动模式下根据时间自动切换'
          options:
            - value: 'auto'
              label: 自动模式
            - value: 'user'
              label: 用户模式
            - value: 'light'
              label: 浅色模式
            - value: 'dark'
              label: 深色模式
        - $formkit: select
          name: font_family
          label: 主题字体
          value: 'null'
          options:
            - value: 'null'
              label: "游览器默认字体"
            - value: "CircularBody"
              label: "CircularBody"
            - value: "HarmonyOS_Regular"
              label: "HarmonyOS_Regular"
        - $formkit: text
          name: content_max_width
          label: 全局内容区最大宽度
          value: '1250px'
          placeholder: 请填写内容区最大宽度
          help: 内容区域最大宽度，像素或百分比，默认 1250px
          validation: required
        - $formkit: radio
          name: enable_assets_link
          label: 启用资源文件加载地址
          help: 必须选配置外链地址才能生效，否则无效，不启用默认为本站地址
          value: 'false'
          options:
            - label: 启用
              value: 'true'
            - label: 禁用
              value: 'false'
          validation: required
        - $formkit: text
          name: assets_link
          label: 资源文件地址
          placeholder: 请填写 资源文件地址
          value: 'https://cdn.jsdelivr.net/npm/halo-theme-butterfly/templates/assets'
          help: '默认为npmJs的jsdelivr加速地址，可自行配置cdn地址（请确保链接下assets文件夹下主题静态资源文件 与 jsdelivr地址中的文件一致），可以填写，否则请勿修改！'
          validation: required


